version: "3"
services:
  fract:
    image: akamjp/fract
    depends_on:
      - mongodb
      - rabbitmq
      - subfracta
      - subfractb
      - subfractc
      - subfractd
      - subfracte
      - subfractf
      - subfractg

  subfracta:
    image: akamjp/fract
    command: fract worker

  subfractb:
    image: akamjp/fract

  subfractc:
    image: akamjp/fract

  subfractd:
    image: akamjp/fract

  subfracte:
    image: akamjp/fract
  
  subfractf:
    image: akamjp/fract

  subfractg:
    image: akamjp/fract

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/db:/data/db
      - ./mongodb/logs:/var/log/mongodb/
    command: mongod --logpath /var/log/mongodb/mongod.log

  rabbitmq:
    image: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq/
