version: "3"
services:
  fract:
    image: akamjp/fract
    depends_on:
      - mongodb
      - rabbitmq
      - mongo-express
      - subfracta
      - subfractb
      - subfractc
      - subfractd
      - subfracte
      - subfractf
      - subfractg
      - subfracth
      - subfracti
      - subfractj

  subfracta:
    image: akamjp/fract
    command: fract worker

  subfractb:
    image: akamjp/fract
    command: fract worker

  subfractc:
    image: akamjp/fract
    command: fract worker

  subfractd:
    image: akamjp/fract
    command: fract worker

  subfracte:
    image: akamjp/fract
    command: fract worker
  
  subfractf:
    image: akamjp/fract
    command: fract worker

  subfractg:
    image: akamjp/fract
    command: fract worker

  subfracth:
    image: akamjp/fract
    command: fract worker

  subfracti:
    image: akamjp/fract
    command: fract worker

  subfractj:
    image: akamjp/fract
    command: fract worker

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/db:/data/db
      - ./mongodb/logs:/var/log/mongodb/
    command: mongod --logpath /var/log/mongodb/mongod.log

  mongo-express:
    image: mongo-express
    environment:
        - ME_CONFIG_MONGODB_SERVER=db
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
    depends_on:
        - mongodb
    ports:
      - "8081:8099"

  rabbitmq:
    image: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq/
