version: "3.6"
services:
  worker:
    image: fract/dev
    depends_on:
      - mongodb
      - rabbitmq
    command: fract worker
  
  fract:
    image: fract/dev
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - ../:/test

  mongodb:
    image: mongo
    restart: always
    #ports:
    #  - "27017:27017"
    #volumes:
    #  - ./mongodb/db:/data/db
    #  - ./mongodb/logs:/var/log/mongodb/
    #command: mongod --logpath /var/log/mongodb/mongod.log

  rabbitmq:
    image: rabbitmq
    #ports:
    #  - "15672:15672"
    #  - "5672:5672"
    #volumes:
    #  - ./rabbitmq:/var/lib/rabbitmq/
